AppBundle\Entity\Highscore:
  type: entity
  table: highscore
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 20
    time:
      type: integer
    coins:
      type: integer